services:
  9router-vfh:
    image: 9router-vfh:latest
    container_name: 9router-vfh
    restart: always
    ports:
      - "2222:2222"
    volumes:
      - 9router-vfh-data:/app/data
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data
      PORT: "2222"
      HOSTNAME: "0.0.0.0"
      NODE_ENV: production
      HEADROOM_URL: http://headroom:8787
    depends_on:
      - headroom

  headroom:
    image: ghcr.io/chopratejas/headroom:latest
    container_name: headroom
    restart: always
    ports:
      - "8787:8787"

volumes:
  9router-vfh-data:
    name: 9router-vfh-data